import { Inter } from "next/font/google";
import "./globals.css";
import MyNavbar from "./components/navbar";
import { UserProvider } from "./contexts/userContext"; // Import UserProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <MyNavbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
